### ISSUE TITLE
how to get the config with the data included?

### ISSUE THREAD

**Issue by monbro** [bestuurszaken/easychart#13]
when I see the demo and the debug tab, I have the full config string with the data included here. But as soon as I do `easyChartInstance.getConfig();` I have the config object without the data within the series attribute. 

How can I get the exact same javascript object as shown in the debug tab?

**Comment by frankbaele** [comment]
hi, quickly expanded the api with getConfigAndData 611d05e4ec2195d1aceb66f3ded2f764913689e3.

Btw if you where importing and exporting this to files or database, use the stringified version of this api.
https://github.com/bestuurszaken/easychart/blob/master/src/js/services/api.js#L57
https://github.com/bestuurszaken/easychart/blob/master/src/js/services/api.js#L69

**Comment by monbro** [comment]
Awesome, thanks for the lightning fast feedback. 

FYI: when downloading version 3.1.0 from https://github.com/bestuurszaken/easychart/releases 'getConfigStringified' is not available - also the version number in comment in the dist folder files is still saying 3.0.0

**Comment by monbro** [comment]
But I am working now with the latest commit of you, the previous comment is just as an info if it makes sense.

**Comment by frankbaele** [comment]
you are correct, I forgot to rebuild it, my bad. I got way too much used to auto building projects these days. new build -> d420c44a492e177d0d7241ad4772fb25758a3499

**Comment by monbro** [comment]
Thanks, works for me - closing this then :)
