### ISSUE TITLE
yAxis type should not be copied/extended from xAxis

### ISSUE THREAD

**Issue by sneakyvv** [bestuurszaken/easychart#2]
If your xAxis' type is "category" and your yAxis has high values, highcharts produces the error "Uncaught Highcharts error #19: www.highcharts.com/errors/19". It's about there being too many ticks, that simply can not be shown on the chart's canvas. 

This is because the yAxis values are being extended with the xAxis values at line 512 in jquery.easychart.js, as is defined at line 10028 in highchartsConfigurationOptions.js. I noticed highchartsConfigurationOptions.js also provides a excluding option for each entry, but this seems to be ignored when extending. A quick fix I used for bestuurszaken.be is to not let the yAxis extend the xAxis, but if the excluding option would be taken into account, then I presume it would be better to set the excluding parameter for the yAxis to "type" so the type is not being copied over.

**Comment by sneakyvv** [comment]
The patch I used

diff --git a/highchartsConfigurationOptions.js b/highchartsConfigurationOptions.js
index 7197e79..0826502 100755
--- a/highchartsConfigurationOptions.js
+++ b/highchartsConfigurationOptions.js
@@ -10025,7 +10025,7 @@ var highchartsConfigurationOptions = {
         "fullname":"yAxis",
         "values":null,
         "title":"yAxis",
-        "extending":"xAxis",
+        "extending":"",
         "excluding":null,
         "isParent":true,
         "since":null,

**Comment by jyve** [comment]
Since we need to do this extending of the YAxis, I would like to see the data you used so that we can achieve the best solution here.
Would it be possible to add your data here, or mail it to me janyves at gmail dot com.
