### ISSUE TITLE
Datetime

### ISSUE THREAD

**Issue by jhallam3** [bestuurszaken/easychart#23]
Hi what format should the date time be in. 

and how can I format it for example MM-DD-YYYY or DD-MMM-YY

thanks

Jon

**Comment by daemth** [comment]
Datetime isn't supported yet the way Highcharts handles it. We plan on adding this in a future release. Until then you can use a date-string and set the x-axis type to "category". Hope that works for now.

**Comment by jhallam3** [comment]
yeh that works for now.

**Comment by daemth** [comment]
Support for timestamp added in fcda6f9.
> Note that datetime axes are based on milliseconds


**Check the demo:**
1. change x-axis type to datetime
2. change labelformat for example to `{value:%Y-%m-%d}`


More about label- and dateformat: 
- http://api.highcharts.com/highcharts/Highcharts.dateFormat
-  http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting

Todo:
- [ ] cleanup
- [ ] support for more datetime-types

**Comment by daemth** [comment]
support for the ISO 8601 date format added in 3129567
> https://en.wikipedia.org/wiki/ISO_8601


**Demo:**
test with _datetime-irregular-intervals.csv_

**Comment by daemth** [comment]
closed in 9e16c53
