### ISSUE TITLE
reversed x axis when inverted graph does not work.

### ISSUE THREAD

**Issue by monstrfolk** [bestuurszaken/easychart#28]
to reproduce

1. create data on graph.
2. Axes > general > click inverted.
3. Axes > x axis > click reversed.

**Comment by daemth** [comment]
In fact, if the chart is inverted, the x axis is reversed by default. So it does work. (This is default Highcharts behaviour: http://api.highcharts.com/highcharts/xAxis.reversed)

When you don't want the xAxis to be reversed if the graph is inverted you should set is to false. unfortunately, Easychart doesn't store values that are equal to the default values so you can't set reversed to false.

**Comment by daemth** [comment]
fiddle: http://jsfiddle.net/e4ro43ad/2/
