### ISSUE TITLE
error when setting options and clicking 'Axes'

### ISSUE THREAD

**Issue by jyve** [bestuurszaken/easychart#5]
When I set the options and then click on 'Axes' in the Customize set, I get an error:

Uncaught TypeError: Cannot read property 'options' of undefined 

As long as I don't set options myself, everything works ok.

**Comment by frankbaele** [comment]
probably related to using ids on a lower level. 
https://github.com/bestuurszaken/easychart/blob/master/src/js/config/options.json#L319
https://github.com/bestuurszaken/easychart/blob/master/src/js/config/options.json#L339
https://github.com/bestuurszaken/easychart/blob/master/src/js/config/options.json#L534
