### ISSUE TITLE
Data loss with gauge chart

### ISSUE THREAD

**Issue by jyve** [bestuurszaken/easychart#6]
When selecting a polar chart (apple watch), the chart looks ok. However the configuration sent through an api call looses some information:

Original version taken from the debug panel:
...
"series": [
  {
    "borderColor": "#7cb5ec",
    "data": [
      {
        "color": "#7cb5ec",
        "radius": "100%",
        "innerRadius": "100%",
        "y": 80
      }
    ],
    "animation": false,
    "name": "Move"
  },

...

Version received after API call:

  "series": [
    {
      "borderColor": "#7cb5ec",
      "animation": false,
      "name": "Move",
      "data": [
        {
          "y": 80
        }
      ]
    },

**Comment by frankbaele** [comment]
related to 
https://github.com/bestuurszaken/easychart/blob/master/src/js/services/config.js#L43

**Comment by daemth** [comment]
almost there, chart looks good now but the icons disappeared after save

**Comment by jyve** [comment]
This is due to #11 , closing this one.
